### register user
POST http://localhost:3500/api/register
Content-Type: application/json

{
    "firstName": "Behdad",
    "lastName": "Mirbani",
    "email": "behdadkindle@gmail.com",
    "password": "behdad1234",
    "confirmPassword": "behdad1234"
  
}

### login user
GET http://localhost:3500/api/verify_token/ec5d2f3204410ea0b65f587f6c08b37c